print("PASSOS PARA ESCOVAR OS DENTES")
print("1) Pegue a escova")
print("2) Coloque um pouco de pasta na escova")
print("3) Escove os dentes por volta de 2 minutos")
print("4) Enxágue a boca com água")
print("5) Enxágue a escova e guarde-a")